name: Auto Approve
# このGitHub Actionsを起動するイベントの種類
on:
  # Pull Request関係のイベント
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review # Draft Pull RequestからDraftが外れたら起動
env:
  HEAD_OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
  HEAD_REPO: ${{ github.event.pull_request.head.repo.name }}

jobs:
  infomation:
    runs-on: ubuntu-latest
    steps:
      # GitHub Actionsのデバッグ用に、Pull Requestの情報を表示する
      - name: Show Pull Request Information
        run: |
          echo "Pull Requestのタイトル: ${{ github.event.pull_request.title }}"
          echo "Pull Requestの作成者: ${{ github.event.pull_request.user.login }}"
          echo "Pull ReqeustのHEADのリポジトリ名: ${{ github.event.pull_request.head.repo.name }}"
          echo "Pull ReqeustのHEADの所有者: ${{ github.event.pull_request.head.repo.owner }}"
          echo "Pull ReqeustのHEADの所有者(login): ${{ github.event.pull_request.head.repo.owner.login }}"
          echo "Pull ReqeustのHEADの所有者(name): ${{ github.event.pull_request.head.repo.owner.name }}"
          echo "Pull Reqeustの所有者の権限: ${{ github.event.pull_request.author_association }}"
          echo "Repositoryの所有者: ${{ github.repository_owner }}"
          echo "Repositoryの所有者(login): ${{ github.repository_owner.login }}"
          echo "Draft Pull Requestかどうか: ${{ github.event.pull_request.draft }}"
  approve:
    # このJobを実行する条件。以下の全てを満たす場合
    # + Pull Requestの作成者が、リポジトリ所有者と等しい
    # + Pull Requestが、Draft Pull Requestではない
    if: |
      github.event.pull_request.user.login == github.repository_owner
      && ! github.event.pull_request.draft
    # このJobを実行する時に使うOS
    # 今回は何でもいいが、GitHub Actionsでは指定が必須
    runs-on: ubuntu-latest
    # 内部で使用されるGitHub APIの権限を上書き
    permissions:
      pull-requests: write
    steps:
      # Pull RequestをApproveする
      - uses: hmarr/auto-approve-action@v3
