name: Micropython Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'dev*'
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.repository }}
  TARGET_PATH: micropython

jobs:
  login:
    permissions:
      packages: write

    runs-on: ubuntu-latest
    steps:
      # Set QEMU for multi platform support
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
            platforms: linux/arm64

      # Recursively checkout all submodules
      - name: Checkout repository with all submodules
        uses: actions/checkout@v4

      - name: Get microptyhon version
        id: micropython-version
        run: |
          echo "MICROPY_VERSION=test02" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.micropython-version.outputs.MICROPY_VERSION }}
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.licenses=MIT

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/development.dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}